steps:
  - id: deploy-prod
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - ${_IMAGE_TAG}
      - --region
      - ${_RUN_REGION}
      - --platform
      - managed
      - --service-account
      - ${_RUNTIME_SERVICE_ACCOUNT}
      - --set-env-vars
      - ^:^FIRESTORE_PROJECT_ID=${_FIRESTORE_PROJECT_ID}:PROFIXIO_HOST=${_PROFIXIO_HOST}:FIRESTORE_DATABASE_ID=${_FIRESTORE_DATABASE_ID}:CORS_HOSTS=${_CORS_HOSTS}:HOST_URL=${_HOST_URL}
      - --set-secrets
      - FIRESTORE_CREDENTIAL_JSON=${_FIRESTORE_CREDENTIAL_SECRET}:latest,PROFIXIO_KEY=${_PROFIXIO_KEY_SECRET}:latest,RESEND_KEY=${_RESEND_KEY_SECRET}:latest

substitutions:
  _ARTIFACT_REGION: europe-west1
  _AR_REPO: tournament-sync
  _IMAGE_NAME: tournament-sync
  _BUILD_SERVICE_ACCOUNT: replace-me@project.iam.gserviceaccount.com
  _IMAGE_TAG: latest
  _ACTION: ""
  _RUN_REGION: europe-west1
  _SERVICE_NAME: tournament-sync-prod
  _RUNTIME_SERVICE_ACCOUNT: replace-me@project.iam.gserviceaccount.com
  _FIRESTORE_PROJECT_ID: scoreboard-sandbox-fc7ac
  _PROFIXIO_HOST: www.profixio.com
  _FIRESTORE_DATABASE_ID: (default)
  _CORS_HOSTS: http://localhost:5173,https://scoreboard-sandbox.herokuapp.com,https://live.osvb.no,https://nt.osvb.no,https://scoreboard-staging-76fc1074c241.herokuapp.com
  _HOST_URL: https://live.osvb.no
  _FIRESTORE_CREDENTIAL_SECRET: tournament-sync-firestore-credentials-prod
  _PROFIXIO_KEY_SECRET: tournament-sync-profixio-key
  _RESEND_KEY_SECRET: tournament-sync-resend-key

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: projects/$PROJECT_ID/serviceAccounts/${_BUILD_SERVICE_ACCOUNT}
