steps:
  - id: verify-release-tag
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -ceu
      - |
        if [[ ! "${TAG_NAME}" =~ ^r[0-9]+$ ]]; then
          echo "Tag '${TAG_NAME}' does not match required pattern ^r[0-9]+$"
          exit 1
        fi

  - id: tag-existing-image-with-release
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - artifacts
      - docker
      - tags
      - add
      - ${_ARTIFACT_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:build-${COMMIT_SHA}
      - ${_ARTIFACT_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:${TAG_NAME}

substitutions:
  _ARTIFACT_REGION: europe-west1
  _AR_REPO: tournament-sync
  _IMAGE_NAME: tournament-sync
  _BUILD_SERVICE_ACCOUNT: replace-me@project.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: projects/$PROJECT_ID/serviceAccounts/${_BUILD_SERVICE_ACCOUNT}
